### ISSUE TITLE
Crash on parsing of Blender 2.8

### ISSUE THREAD

**Issue by fabsx00** [ShiftLeftSecurity/joern#126]
To reproduce, run `./joern-parse` on the blender source code at: https://github.com/sobotka/blender/releases/tag/v2.80
```
[main] ERROR io.shiftleft.joern.JoernParse$ - Failed to enhance CPG.
java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at io.shiftleft.fuzzyc2cpg.parser.modules.CModuleParserTreeListener.enterTemplate_decl(CModuleParserTreeListener.java:113)
	at io.shiftleft.fuzzyc2cpg.ModuleParser$Template_declContext.enterRule(ModuleParser.java:3505)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:42)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:25)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at io.shiftleft.fuzzyc2cpg.parser.AntlrParserDriver.walkTree(AntlrParserDriver.java:177)
	at io.shiftleft.fuzzyc2cpg.parser.AntlrParserDriver.parseAndWalkTokenStream(AntlrParserDriver.java:123)
	at io.shiftleft.fuzzyc2cpg.parser.modules.CModuleParserTreeListener.parseClassContent(CModuleParserTreeListener.java:198)
	at io.shiftleft.fuzzyc2cpg.parser.modules.CModuleParserTreeListener.exitDeclByClass(CModuleParserTreeListener.java:167)
	at io.shiftleft.fuzzyc2cpg.ModuleParser$DeclByClassContext.exitRule(ModuleParser.java:2174)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:47)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:30)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at io.shiftleft.fuzzyc2cpg.parser.AntlrParserDriver.walkTree(AntlrParserDriver.java:177)
	at io.shiftleft.fuzzyc2cpg.parser.AntlrParserDriver.parseAndWalkFile(AntlrParserDriver.java:78)
	at io.shiftleft.fuzzyc2cpg.FuzzyC2Cpg.createCpgForCompilationUnit(FuzzyC2Cpg.scala:171)
	at io.shiftleft.fuzzyc2cpg.FuzzyC2Cpg.$anonfun$runAndOutput$1(FuzzyC2Cpg.scala:87)
	at io.shiftleft.fuzzyc2cpg.FuzzyC2Cpg.$anonfun$runAndOutput$1$adapted(FuzzyC2Cpg.scala:87)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.parallel.immutable.ParHashSet$ParHashSetIterator.foreach(ParHashSet.scala:81)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:974)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:971)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:170)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
	Suppressed: java.util.EmptyStackException
		... 43 more
		Suppressed: java.util.EmptyStackException
			at java.util.Stack.peek(Stack.java:102)
			at io.shiftleft.fuzzyc2cpg.parser.modules.CModuleParserTreeListener.enterTemplate_decl(CModuleParserTreeListener.java:113)
			at io.shiftleft.fuzzyc2cpg.ModuleParser$Template_declContext.enterRule(ModuleParser.java:3505)
			at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:42)
			at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:25)
			at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
			... 28 more
			Suppressed: java.util.EmptyStackException
				at java.util.Stack.peek(Stack.java:102)
				at io.shiftleft.fuzzyc2cpg.parser.modules.CModuleParserTreeListener.enterTemplate_decl(CModuleParserTreeListener.java:113)
				at io.shiftleft.fuzzyc2cpg.ModuleParser$Template_declContext.enterRule(ModuleParser.java:3505)
				at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:42)
				at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:25)
				at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
				at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
				at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
				at io.shiftleft.fuzzyc2cpg.parser.AntlrParserDriver.walkTree(AntlrParserDriver.java:177)
				at io.shiftleft.fuzzyc2cpg.parser.AntlrParserDriver.parseAndWalkTokenStream(AntlrParserDriver.java:123)
				at io.shiftleft.fuzzyc2cpg.parser.modules.CModuleParserTreeListener.parseClassContent(CModuleParserTreeListener.java:198)
				at io.shiftleft.fuzzyc2cpg.parser.modules.CModuleParserTreeListener.exitDeclByClass(CModuleParserTreeListener.java:167)
				at io.shiftleft.fuzzyc2cpg.ModuleParser$DeclByClassContext.exitRule(ModuleParser.java:2174)
				at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:47)
				at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:30)
				... 28 more
				Suppressed: java.util.EmptyStackException
					at java.util.Stack.peek(Stack.java:102)
					at io.shiftleft.fuzzyc2cpg.parser.modules.CModuleParserTreeListener.enterTemplate_decl(CModuleParserTreeListener.java:113)
					at io.shiftleft.fuzzyc2cpg.ModuleParser$Template_declContext.enterRule(ModuleParser.java:3505)
					at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:42)
					at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:25)
					at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
					... 28 more


```

**Comment by fabsx00** [comment]
Mitigated via https://github.com/ShiftLeftSecurity/fuzzyc2cpg/pull/131 - but further investigation by @GlassAndOneHalf required.

**Comment by derpsteb** [comment]
I just got the same error upon trying to parse [spidermonkey's jit compiler](https://github.com/mozilla/gecko-dev/commit/70553d3b7766aae5605297f7fa1138edae0b9050).

Going from the previous comment there should be a cpg, but there is none. 

The build works as parsing the testfile or other single files of spidermonkey works fine.
scalaVersion := "2.12.8"
cpgVersion = "0.10.78"
fuzzyc2cpgVersion = "0.1.114"

**Comment by fabsx00** [comment]
Yes, there should be a CPG, and also, you should see this message: https://github.com/ShiftLeftSecurity/fuzzyc2cpg/pull/131/files#diff-0e4b0dd2cac759f7aa8f05dd45cdadb6R176
If you do not see that message, then you're not using the most recent version of fuzzyc2cpg yet. Could you check?

**Comment by derpsteb** [comment]
Hm, weird. I retried it just now and it worked. Sorry for the noise.

**Comment by GlassAndOneHalf** [comment]
Looks like this is caused by function declarations missing explicit parameter names, e.g.
```scala
template <class C> C foo(C);
```

**Comment by GlassAndOneHalf** [comment]
Fixed 2 out of 3 Blender crashes with https://github.com/ShiftLeftSecurity/fuzzyc2cpg/pull/148

Investigating the cause of the final one.

**Comment by GlassAndOneHalf** [comment]
The final issue seems to be caused by default parameters. Adding support for these in our grammar now...

Example:
```scala
template <typename A> 
A do_a(A& a = x);
```

**Comment by GlassAndOneHalf** [comment]
Fix for the remaining exception:
https://github.com/ShiftLeftSecurity/fuzzyc2cpg/pull/149
