### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by anon767** [ShiftLeftSecurity/joern#367]
Hi,

I get following Exception when trying to import _any_ project with joern-cli:

`
joern> importCode(inputPath="./x42/c", projectName="x42-c")
Creating project `x42-c` for code at `./x42/c`
java.lang.NoClassDefFoundError: jdk/nashorn/internal/runtime/ParserException
	at io.shiftleft.fuzzyc2cpg.passes.AstCreationPass.createDriver(AstCreationPass.scala:42)
	at io.shiftleft.fuzzyc2cpg.passes.AstCreationPass.runOnPart(AstCreationPass.scala:36)
	at io.shiftleft.fuzzyc2cpg.passes.AstCreationPass.runOnPart(AstCreationPass.scala:14)
	at io.shiftleft.passes.ParallelCpgPass.$anonfun$enqueueInParallel$2(ParallelCpgPass.scala:58)
	at io.shiftleft.passes.ParallelCpgPass.$anonfun$enqueueInParallel$2$adapted(ParallelCpgPass.scala:53)
	at io.shiftleft.passes.ParallelIteratorExecutor.$anonfun$map$2(ParallelIteratorExecutor.scala:11)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:660)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
	at scala.concurrent.BatchingExecutor$AbstractBatch.runN(BatchingExecutor.scala:134)
	at scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:163)
	at scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:146)
	at scala.concurrent.BlockContext$.usingBlockContext(BlockContext.scala:107)
	at scala.concurrent.BatchingExecutor$AsyncBatch.run(BatchingExecutor.scala:154)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1429)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ClassNotFoundException: jdk.nashorn.internal.runtime.ParserException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 19 more
`

Versions used:
- OpenJDK 15 2020-09-15
- Joern-CLI 1.1.29 (tested both: prebuilt and self-compiled)

tested with:

git clone https://github.com/ShiftLeftSecurity/x42.git

joern> importCode(inputPath="./x42/c", projectName="x42-c")

**Comment by anon767** [comment]
Nevermind, works with OpenJDK < 15
