### ISSUE TITLE
Jar import support

### ISSUE THREAD

**Issue by prabhu** [ShiftLeftSecurity/joern#450]
I was trying to import a jar as code and received meta node related error. Any ideas?

```
importCode("/Users/prabhu/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.12.1/jackson-databind-2.12.1.jar")
Using generator for language: JAVA
Creating project `jackson-databind-2.12.1.jar` for code at `/Users/prabhu/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.12.1/jackson-databind-2.12.1.jar`
/var/folders/tj/qpj19ty13n193twz68w6phj80000gn/T/jackson-databind-2.12.1.jar8776038529332784731
moving cpg.bin.zip to cpg.bin because it is already a database file
Creating working copy of CPG to be safe
Loading base CPG from: /Users/prabhu/joern-cli/workspace/jackson-databind-2.12.1.jar/cpg.bin.tmp
Missing metaData block
Adding default overlays to base CPG
Missing metaData block
Missing metaData block
java.lang.Exception: Meta node missing.
  io.shiftleft.semanticcpg.layers.Scpg.$anonfun$create$1(Scpg.scala:41)
  scala.Option.getOrElse(Option.scala:202)
  io.shiftleft.semanticcpg.layers.Scpg.create(Scpg.scala:41)
  io.shiftleft.semanticcpg.layers.LayerCreator.run(LayerCreator.scala:34)
  io.shiftleft.console.Console.runCreator(Console.scala:427)
  io.shiftleft.console.Console.$anonfun$_runAnalyzer$1(Console.scala:417)
  io.shiftleft.console.Console.$anonfun$_runAnalyzer$1$adapted(Console.scala:404)
  scala.collection.immutable.List.foreach(List.scala:312)
  io.shiftleft.console.Console._runAnalyzer(Console.scala:404)
  io.shiftleft.console.Console.applyDefaultOverlays(Console.scala:397)
  io.shiftleft.console.cpgcreation.ImportCode.$anonfun$apply$10(ImportCode.scala:134)
  scala.Option.map(Option.scala:243)
  io.shiftleft.console.cpgcreation.ImportCode.$anonfun$apply$7(ImportCode.scala:133)
  scala.Option.flatMap(Option.scala:284)
  io.shiftleft.console.cpgcreation.ImportCode.$anonfun$apply$6(ImportCode.scala:124)
  scala.Option.flatMap(Option.scala:284)
  io.shiftleft.console.cpgcreation.ImportCode.io$shiftleft$console$cpgcreation$ImportCode$$apply(ImportCode.scala:123)
  io.shiftleft.console.cpgcreation.ImportCode.$anonfun$apply$2(ImportCode.scala:44)
  scala.Option.flatMap(Option.scala:284)
  io.shiftleft.console.cpgcreation.ImportCode.apply(ImportCode.scala:43)
  ammonite.$sess.cmd0$.<clinit>(cmd0.sc:1)
```

**Comment by fabsx00** [comment]
While this feature isn't really launched yet, I was under the impression that this already works, so, let me take a look.

**Comment by fabsx00** [comment]
I can reproduce it.

**Comment by fabsx00** [comment]
This looks like an issue in plume. I'll try upgrading first as there have been many fixes.

**Comment by fabsx00** [comment]
Turns out that joern swallows the following exception thrown in plume:
```
java.lang.UnsupportedOperationException: This feature requires ASM6
	at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:143)
	at org.objectweb.asm.ClassReader.readModuleAttributes(ClassReader.java:755)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:554)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at io.github.plume.oss.util.ResourceCompilationUtil.moveClassFiles(ResourceCompilationUtil.kt:111)
	at io.github.plume.oss.Extractor.compileLoadedFiles(Extractor.kt:220)
	at io.github.plume.oss.Extractor.project(Extractor.kt:236)
	at io.shiftleft.joern.plume.PlumeCpgGenerator$.$anonfun$createCpgForDirectory$2(PlumeCpgGenerator.scala:34)
	at io.shiftleft.joern.plume.PlumeCpgGenerator$.$anonfun$createCpgForDirectory$2$adapted(PlumeCpgGenerator.scala:29)
	at scala.util.Using$.$anonfun$apply$1(Using.scala:261)
	at scala.util.Using$.apply(Using.scala:113)
	at io.shiftleft.joern.plume.PlumeCpgGenerator$.createCpgForDirectory(PlumeCpgGenerator.scala:29)
	at io.shiftleft.joern.plume.PlumeCpgGenerator$.createCpgForArchive(PlumeCpgGenerator.scala:48)
	at io.shiftleft.joern.plume.PlumeCpgGenerator$.$anonfun$createCpgForJava$1(PlumeCpgGenerator.scala:21)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:168)
	at io.shiftleft.joern.plume.PlumeCpgGenerator$.createCpgForJava(PlumeCpgGenerator.scala:13)
	at io.shiftleft.joern.JoernParse$.generateCpg(JoernParse.scala:25)
	at io.shiftleft.joern.JoernParse$.$anonfun$new$1(JoernParse.scala:12)
	at io.shiftleft.joern.JoernParse$.$anonfun$new$1$adapted(JoernParse.scala:10)
	at scala.Option.foreach(Option.scala:437)
	at io.shiftleft.joern.JoernParse$.delayedEndpoint$io$shiftleft$joern$JoernParse$1(JoernParse.scala:10)
	at io.shiftleft.joern.JoernParse$delayedInit$body.apply(JoernParse.scala:7)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at io.shiftleft.joern.JoernParse$.main(JoernParse.scala:7)
	at io.shiftleft.joern.JoernParse.main(JoernParse.scala)
```
On the joern side, I will ensure that plume's exceptions are reported correctly and I will file a follow-up ticket in plume.

**Comment by fabsx00** [comment]
https://github.com/plume-oss/plume/pull/49

**Comment by fabsx00** [comment]
This particular crash is fixed by https://github.com/ShiftLeftSecurity/joern/pull/453, however, there is a follow-up crash, so, I won't close this ticket yet.

**Comment by DavidBakerEffendi** [comment]
> This particular crash is fixed by #453, however, there is a follow-up crash, so, I won't close this ticket yet.
> 
> ```
> java.lang.Exception: Unknown binary operator $stack1 cmp -2147483648L
> 	at io.github.plume.oss.graph.ASTBuilder.projectBinopExpr(ASTBuilder.kt:401)
> 	at io.github.plume.oss.graph.ASTBuilder.projectOp(ASTBuilder.kt:499)
> 	at io.github.plume.oss.graph.ASTBuilder.projectVariableAssignment(ASTBuilder.kt:380)
> 	at io.github.plume.oss.graph.ASTBuilder.projectUnit(ASTBuilder.kt:118)
> 	at io.github.plume.oss.graph.ASTBuilder.buildMethodBody(ASTBuilder.kt:67)
> 	at io.github.plume.oss.Extractor.constructCPG(Extractor.kt:309)
> 	at io.github.plume.oss.Extractor.project(Extractor.kt:258)
> ```

I have made a fix in my latest branch which will also log a warning instead of throwing an exception in similar events

**Comment by fabsx00** [comment]
Nice! Let me know when it's released so that we can test this and potentially close the issue.

**Comment by fabsx00** [comment]
https://github.com/ShiftLeftSecurity/joern/pull/454

**Comment by fabsx00** [comment]
Good news: we're not crashing anymore
Bad news: it doesn't terminate in a timely manner either.
I attached a profiler, here's what it says:
![profiler](https://user-images.githubusercontent.com/1379115/106632784-6a61a180-657e-11eb-9433-72ad706affec.png)

**Comment by fabsx00** [comment]
Seems to be this query that takes so long:
```
 Cpg(graph).file.ast.outE(EdgeTypes.AST).l.asJava
```
which makes sense as it enumerates pretty much all nodes of the graph. Looking...

**Comment by fabsx00** [comment]
https://github.com/plume-oss/plume/pull/51
