### ISSUE TITLE
Exception of "GC overhead limit exceeded" occur when prase bintuils 2.28

### ISSUE THREAD

**Issue by wcventure** [ShiftLeftSecurity/joern#55]
Hi there,

I try to use the following command ` ./joern-parse ./binutils-2.28/` to prase the CPG for binutils, but an Exception. Is the CPG extracted in this way complete? What happened?

```
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label default_reloc.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label default_reloc.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label default_reloc.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label default_reloc.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label default_reloc.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label default_reloc.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label default_reloc.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label default_reloc.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label default_reloc.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label default_reloc.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label default_reloc.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label default_reloc.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label default_reloc.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label default_reloc.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label default_reloc.

Error parsing function write_rc_dialog_control. skipping.
Error parsing function write_rc_messagetable. skipping.
Error parsing function insert_reg_alias. skipping.
Error parsing function mmix_cons. skipping.
Error parsing function ppc_target_format. skipping.

Error parsing function rx_include. skipping.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label default_case.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label default_case.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label default_case.
Error parsing function Arm_exidx_cantunwind::do_fixed_endian_write. skipping.
Error parsing function lay_out_got. skipping.
Error parsing function General_options::parse_R. skipping.
Error parsing function locale_charset. skipping.
Error parsing function lang_output_section_statement_lookup. skipping.
Error parsing function get_DW_TAG_name. skipping.
Error parsing function print_and_abort. skipping.
Error parsing function (extract_number). skipping.
Error parsing function (print_partial_compiled_pattern). skipping.
Error parsing function byte_compile_range. skipping.
Error parsing function truncate_wchar. skipping.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label case_S.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label case_S.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label case_Q.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label case_P.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label case_L.
[main] WARN io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label case_B.
Error parsing function main. skipping.
Error parsing function zlibCompileFlags. skipping.
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at io.shiftleft.proto.cpg.Cpg$PropertyValue$1.parsePartialFrom(Cpg.java:3587)
        at io.shiftleft.proto.cpg.Cpg$PropertyValue$1.parsePartialFrom(Cpg.java:3581)
        at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2361)
        at io.shiftleft.proto.cpg.Cpg$CpgStruct$Node$Property.<init>(Cpg.java:8143)
        at io.shiftleft.proto.cpg.Cpg$CpgStruct$Node$Property.<init>(Cpg.java:8095)
        at io.shiftleft.proto.cpg.Cpg$CpgStruct$Node$Property$1.parsePartialFrom(Cpg.java:8751)
        at io.shiftleft.proto.cpg.Cpg$CpgStruct$Node$Property$1.parsePartialFrom(Cpg.java:8745)
        at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2361)
        at io.shiftleft.proto.cpg.Cpg$CpgStruct$Node.<init>(Cpg.java:7387)
        at io.shiftleft.proto.cpg.Cpg$CpgStruct$Node.<init>(Cpg.java:7331)
        at io.shiftleft.proto.cpg.Cpg$CpgStruct$Node$1.parsePartialFrom(Cpg.java:9555)
        at io.shiftleft.proto.cpg.Cpg$CpgStruct$Node$1.parsePartialFrom(Cpg.java:9549)
        at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2361)
        at io.shiftleft.proto.cpg.Cpg$CpgStruct.<init>(Cpg.java:7236)
        at io.shiftleft.proto.cpg.Cpg$CpgStruct.<init>(Cpg.java:7192)
        at io.shiftleft.proto.cpg.Cpg$CpgStruct$1.parsePartialFrom(Cpg.java:12744)
        at io.shiftleft.proto.cpg.Cpg$CpgStruct$1.parsePartialFrom(Cpg.java:12738)
        at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:215)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:232)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:237)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
        at com.google.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:317)
        at io.shiftleft.proto.cpg.Cpg$CpgStruct.parseFrom(Cpg.java:11950)
        at io.shiftleft.codepropertygraph.cpgloading.ProtoCpgLoader.getNextProtoCpgFromStream(ProtoCpgLoader.java:193)
        at io.shiftleft.codepropertygraph.cpgloading.ProtoCpgLoader.loadFromProtobufDirectory(ProtoCpgLoader.java:137)
        at io.shiftleft.codepropertygraph.cpgloading.ProtoCpgLoader.loadFromProtoZip(ProtoCpgLoader.java:43)
        at io.shiftleft.codepropertygraph.cpgloading.CpgLoader.load(CpgLoader.scala:68)
        at io.shiftleft.codepropertygraph.cpgloading.CpgLoader$.load(CpgLoader.scala:38)
        at io.shiftleft.joern.CpgLoader$.load(CpgLoader.scala:20)
        at io.shiftleft.joern.Cpg2Scpg$.run(Cpg2Scpg.scala:14)
        at io.shiftleft.joern.JoernParse$.parse(JoernParse.scala:24)
        at io.shiftleft.joern.JoernParse$.$anonfun$new$1(JoernParse.scala:13)
```

**Comment by wcventure** [comment]
Another question is that can joern support the whole project rather than some few functions? I hope I can extract CPG from the whole project and do some inter-process analysis.

**Comment by fabsx00** [comment]
Added comment about tuning the JVM memory settings: https://github.com/ShiftLeftSecurity/joern/pull/59
